# Config file for automatic testing at travis-ci.org

language: python
python:
  - 2.7

install: pip install coveralls


before_install:
- pip install coverage
- pip install numpy
- pip install matplotlib
- pip install scipy
- pip install argparse

script:
- coverage run --source=langevin/langevin.py setup.py test
- coverage report -m

after_success: coveralls

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: tttianhao
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: tttianhao/langevin
    python: 3.6
